FROM registry.cn-shenzhen.aliyuncs.com/artcoding/php-fpm7.2:dev
COPY ./conf/conf.d/docker-php-ext-xdebug.ini  /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
ENV PATH=$HOME/.config/composer/vendor/bin:${PATH}